# Cloudflare config (remove this file if you're not using the Cloudflare adapter)
name = "blog"
compatibility_date = "2025-08-15"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]
send_metrics = false

[placement]
mode = "smart"
