# Cloudflare config (remove this file if you're not using Cloudflare Workers)
name = "blog"
compatibility_date = "2024-06-05"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]
send_metrics = false
